name: Run Gradle on PRs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ./gradlew build
    - name: test
      run: ./gradlew test
    - name: testOn16
      run: ./gradlew testOn16
    - name: run
      run: ./gradlew run
    - name: run
      run: ./gradlew runOn20
